metadata:
  namespace: ${helm_namespace}
  labels:
    project: ${name}
    version: ${version}
    app.kubernetes.io/name: ${name}
    app.kubernetes.io/instance: ${helm_release_name}
    app.kubernetes.io/version: ${version}
    app.kubernetes.io/part-of: ${name}
    app.kubernetes.io/managed-by: helm
type: Opaque
stringData:
  application-k8s.properties: |
    spring.config.import="optional:configtree:/app/run/config/"
    spring.datasource.url=jdbc:postgresql://${postgres.fullnameOverride}:5432/${postgres.userDatabase.name}
    spring.datasource.username=${postgres.userDatabase.user}
    spring.datasource.password=${postgres.userDatabase.password}
